name: Release
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: node-version
        uses: actions/setup-node@main
        with:
          node-version: '12'
      - name: npm-install
        run: npm install
      - name: test
        run: npm test
      - name: build
        run: npm run build
      - name: Coverage
        run: npx codecov -t ${{ secrets.CODECOV_TOKEN }}
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
